# /// script
# requires-python = ">=3.13,<3.14"
# dependencies = []
# ///
"""Landmark procedure step E: mirror the manifest into a migration and the geojson.
Run: uv run model/scripts/landmarks_sql.py   (writes one new migration covering every manifest entry)"""
import datetime
import json

from common import ROOT

MANIFEST = ROOT / "model" / "out" / "landmarks-manifest.json"
GEO = ROOT / "data" / "geojson" / "landmarks.geojson"


def q(s):
    return "'" + str(s).replace("'", "''") + "'"


def main():
    entries = json.loads(MANIFEST.read_text())["landmarks"]
    stamp = datetime.datetime.now(datetime.UTC).strftime("%Y%m%d%H%M%S")
    lines = ["-- Landmark meshes, generated by model/scripts/landmarks_sql.py from model/out/landmarks-manifest.json.",
             "-- Live destination ids differ from the seed's, so rows are matched by slug. Idempotent.", "DO $$", "DECLARE n integer;", "BEGIN"]
    for e in entries:
        lines += [
            f"  DELETE FROM \"landmarks\" WHERE \"destination_id\" = (SELECT \"id\" FROM \"destinations\" WHERE \"slug\" = {q(e['slug'])});",
            "  INSERT INTO \"landmarks\" (\"id\", \"destination_id\", \"mesh_url\", \"mesh_scale\", \"rotation_deg\", \"altitude_m\")",
            f"  SELECT gen_random_uuid()::text, \"id\", {q(e['url'])}, 1, {e['rotationDeg']}, {e['altitudeM']} FROM \"destinations\" WHERE \"slug\" = {q(e['slug'])};",
            "  GET DIAGNOSTICS n = ROW_COUNT;",
            f"  IF n <> 1 THEN RAISE EXCEPTION 'landmarks: {e['slug']} expected 1 row, inserted %', n; END IF;",
        ]
    lines += ["END", "$$;", ""]
    out = ROOT / "supabase" / "migrations" / f"{stamp}_landmark_meshes.sql"
    out.write_text("\n".join(lines))
    # Edit only each meshUrl value in place: re-serialising would reformat the whole file (and its coordinates).
    text = GEO.read_text()
    for f in json.loads(text)["features"]:
        slug = f["properties"]["slug"]
        url = next((e["url"] for e in entries if e["slug"] == slug), None)
        i = text.index(f'"slug": "{slug}"')
        j = text.index('"meshUrl":', i)
        k = text.index("\n", j)
        comma = "," if text[j:k].rstrip().endswith(",") else ""
        text = text[:j] + f'"meshUrl": {json.dumps(url)}{comma}' + text[k:]
    GEO.write_text(text)
    print(f"wrote {out.relative_to(ROOT)} ({len(entries)} landmark(s)); synced meshUrl in {GEO.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
