# /// script
# requires-python = ">=3.13,<3.14"
# dependencies = []
# ///
"""Move each destination pin onto its 3D model (owner decision 2026-10-06): the pins were 78 m to 5.1 km from their
places (Igorot Stone Kingdom 5.1 km), so opening a sheet flew the map away from the model.
- New coordinate: the model's anchor in model/landmarks.json (the centroid of its cited OSM footprint).
- elevation_m: resampled there from the AWS Terrarium DEM at z15, the way scripts/fix-elevations.py does it.
- Mile-Hi: the name and description are corrected (no view deck exists; model/landmarks/mile-hi-cjh-viewdeck.md).
Edits data/geojson/landmarks.geojson in place (keeping its formatting) and writes one migration.
Run: uv run model/scripts/move_pins.py   (then npm run seed:supabase:generate)"""
import datetime
import importlib.util
import json
import re

from common import LANDMARKS, ROOT

spec = importlib.util.spec_from_file_location("probe", ROOT / "scripts" / "baguio-dem-probe.py")
probe = importlib.util.module_from_spec(spec)
spec.loader.exec_module(probe)

GEO = ROOT / "data" / "geojson" / "landmarks.geojson"
TEXT_FIXES = {
    "mile-hi-cjh-viewdeck": {
        "name": "Mile Hi Center, Camp John Hay",
        "description": ("The former American commissary in Camp John Hay, named for its elevation of about a mile, now a row of "
                        "shops and eateries under a covered walkway. Once known for bowling, billiards and arcade games, it "
                        "reopened in August 2025 after six years closed, with cafes, a grill and a weekend market for Baguio's "
                        "farmers and makers."),
    },
}


def sql_text(s):
    return "'" + s.replace("'", "''") + "'"


def main():
    reg = json.loads(LANDMARKS.read_text())
    text = GEO.read_text()
    doc = json.loads(text)
    stamp = datetime.datetime.now(datetime.UTC).strftime("%Y%m%d%H%M%S")
    sql = ["-- Destination pins moved onto their 3D models (model/landmarks.json anchors, from cited OSM footprints),",
           "-- elevation_m resampled from the AWS Terrarium DEM at z15; generated by model/scripts/move_pins.py. Idempotent.",
           "DO $$", "DECLARE n integer;", "BEGIN"]
    for feature in doc["features"]:
        slug = feature["properties"]["slug"]
        anchor = reg.get(slug, {}).get("anchor")
        if not anchor:
            continue
        lng, lat = anchor
        elev = round(probe.elevation(lng, lat, z=15)[0])
        old = feature["geometry"]["coordinates"]
        # each feature is {"type": "Feature", "geometry": {...}, "properties": {...}}: edit only its own block
        at = text.index(f'"slug": "{slug}"')
        fstart = text.rfind('"type": "Feature"', 0, at)
        fend = text.find('"type": "Feature"', at)
        fend = len(text) if fend < 0 else fend
        block = text[fstart:fend]
        block, n1 = re.subn(r'"coordinates": \[[^\]]*\]', f'"coordinates": [{lng}, {lat}]', block, count=1)
        block, n2 = re.subn(r'("elevation_m": )(null|-?\d+(?:\.\d+)?)', rf"\g<1>{elev}", block, count=1)
        assert n1 == 1 and n2 == 1, f"{slug}: coordinates or elevation_m not found"
        fixes = TEXT_FIXES.get(slug, {})
        for key, value in fixes.items():
            block, n = re.subn(rf'("{key}": )"(?:[^"\\]|\\.)*"', lambda m: m.group(1) + json.dumps(value), block, count=1)
            assert n == 1, f"{slug}: {key} not found"
        text = text[:fstart] + block + text[fend:]
        sets = [f"geom = ST_SetSRID(ST_MakePoint({lng}, {lat}), 4326)", f"elevation_m = {elev}"]
        sets += [f'"{k}" = {sql_text(v)}' for k, v in fixes.items()]
        sql += [f"  UPDATE \"destinations\" SET {', '.join(sets)} WHERE \"slug\" = '{slug}';",
                "  GET DIAGNOSTICS n = ROW_COUNT;",
                f"  IF n <> 1 THEN RAISE EXCEPTION 'destinations: {slug} expected 1 row, updated %', n; END IF;"]
        print(f"{slug:30s} {old} -> [{lng}, {lat}]  elevation {elev}" + ("  + name/description" if fixes else ""))
    sql += ["END $$;"]
    GEO.write_text(text)
    out = ROOT / "supabase" / "migrations" / f"{stamp}_move_destination_pins.sql"
    out.write_text("\n".join(sql) + "\n")
    json.loads(GEO.read_text())   # still valid JSON
    print(f"wrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
