-- Burnham visited Baguio in December 1904; his plan for the city is dated 1905.
-- Brings the three affected rows in line with supabase/seed.sql. Row ids are
-- left alone: live ids were not generated by the seed script.
DO $$
DECLARE
  n integer;
BEGIN
  UPDATE "historical_eras"
  SET "summary" = 'American authorities, seeking a cool refuge from lowland heat, transformed Kafagway into a planned summer capital. Architect Daniel Burnham''s 1905 plan gave the city its park, radial roads, and civic core, while the hand-carved Kennon Road linked it to the lowlands. Chartered in 1909, Baguio grew into the ''City of Pines,'' a hub of government, mining wealth, and mountain leisure.'
  WHERE "key" = 'AMERICAN_COLONIAL';
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION 'historical_eras: expected 1 row, updated %', n; END IF;

  UPDATE "destinations"
  SET "description" = 'The green heart of Baguio, laid out to Daniel Burnham''s 1905 city plan around a man-made lagoon where visitors paddle rented boats. Its tree-lined lanes, rose garden, and skating rink draw families and cyclists at every hour. On cool mornings the melody of buskers and the scent of pine define the city''s leisurely rhythm.'
  WHERE "slug" = 'burnham-park';
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION 'destinations: expected 1 row, updated %', n; END IF;

  UPDATE "historical_events"
  SET "year" = 1905,
      "description" = 'Architect Daniel Hudson Burnham surveyed the plateau in December 1904 and drafted a city plan centered on a park, a civic core, and radiating avenues. His vision shaped the layout of Baguio that endures today.'
  WHERE "title" = 'Burnham Plan for the Summer Capital';
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION 'historical_events: expected 1 row, updated %', n; END IF;
END
$$;
