-- Landmark meshes, generated by model/scripts/landmarks_sql.py from model/out/landmarks-manifest.json.
-- Live destination ids differ from the seed's, so rows are matched by slug. Idempotent.
DO $$
DECLARE n integer;
BEGIN
  DELETE FROM "landmarks" WHERE "destination_id" = (SELECT "id" FROM "destinations" WHERE "slug" = 'baguio-cathedral');
  INSERT INTO "landmarks" ("id", "destination_id", "mesh_url", "mesh_scale", "rotation_deg", "altitude_m")
  SELECT gen_random_uuid()::text, "id", '/models/landmarks/baguio-cathedral.af87b1fd.glb', 1, 0, 0 FROM "destinations" WHERE "slug" = 'baguio-cathedral';
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION 'landmarks: baguio-cathedral expected 1 row, inserted %', n; END IF;
  DELETE FROM "landmarks" WHERE "destination_id" = (SELECT "id" FROM "destinations" WHERE "slug" = 'baguio-city-hall');
  INSERT INTO "landmarks" ("id", "destination_id", "mesh_url", "mesh_scale", "rotation_deg", "altitude_m")
  SELECT gen_random_uuid()::text, "id", '/models/landmarks/baguio-city-hall.cbcb7ab3.glb', 1, 0, 0 FROM "destinations" WHERE "slug" = 'baguio-city-hall';
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION 'landmarks: baguio-city-hall expected 1 row, inserted %', n; END IF;
  DELETE FROM "landmarks" WHERE "destination_id" = (SELECT "id" FROM "destinations" WHERE "slug" = 'baguio-museum');
  INSERT INTO "landmarks" ("id", "destination_id", "mesh_url", "mesh_scale", "rotation_deg", "altitude_m")
  SELECT gen_random_uuid()::text, "id", '/models/landmarks/baguio-museum.f43a1245.glb', 1, 0, 0 FROM "destinations" WHERE "slug" = 'baguio-museum';
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION 'landmarks: baguio-museum expected 1 row, inserted %', n; END IF;
  DELETE FROM "landmarks" WHERE "destination_id" = (SELECT "id" FROM "destinations" WHERE "slug" = 'baguio-public-market');
  INSERT INTO "landmarks" ("id", "destination_id", "mesh_url", "mesh_scale", "rotation_deg", "altitude_m")
  SELECT gen_random_uuid()::text, "id", '/models/landmarks/baguio-public-market.052c7214.glb', 1, 0, 0 FROM "destinations" WHERE "slug" = 'baguio-public-market';
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION 'landmarks: baguio-public-market expected 1 row, inserted %', n; END IF;
  DELETE FROM "landmarks" WHERE "destination_id" = (SELECT "id" FROM "destinations" WHERE "slug" = 'bencab-museum');
  INSERT INTO "landmarks" ("id", "destination_id", "mesh_url", "mesh_scale", "rotation_deg", "altitude_m")
  SELECT gen_random_uuid()::text, "id", '/models/landmarks/bencab-museum.3c40e9f6.glb', 1, 0, 0 FROM "destinations" WHERE "slug" = 'bencab-museum';
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION 'landmarks: bencab-museum expected 1 row, inserted %', n; END IF;
  DELETE FROM "landmarks" WHERE "destination_id" = (SELECT "id" FROM "destinations" WHERE "slug" = 'botanical-garden');
  INSERT INTO "landmarks" ("id", "destination_id", "mesh_url", "mesh_scale", "rotation_deg", "altitude_m")
  SELECT gen_random_uuid()::text, "id", '/models/landmarks/botanical-garden.8992d321.glb', 1, 0, 0 FROM "destinations" WHERE "slug" = 'botanical-garden';
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION 'landmarks: botanical-garden expected 1 row, inserted %', n; END IF;
  DELETE FROM "landmarks" WHERE "destination_id" = (SELECT "id" FROM "destinations" WHERE "slug" = 'burnham-park');
  INSERT INTO "landmarks" ("id", "destination_id", "mesh_url", "mesh_scale", "rotation_deg", "altitude_m")
  SELECT gen_random_uuid()::text, "id", '/models/landmarks/burnham-park.afb85f57.glb', 1, 0, 0 FROM "destinations" WHERE "slug" = 'burnham-park';
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION 'landmarks: burnham-park expected 1 row, inserted %', n; END IF;
  DELETE FROM "landmarks" WHERE "destination_id" = (SELECT "id" FROM "destinations" WHERE "slug" = 'camp-john-hay');
  INSERT INTO "landmarks" ("id", "destination_id", "mesh_url", "mesh_scale", "rotation_deg", "altitude_m")
  SELECT gen_random_uuid()::text, "id", '/models/landmarks/camp-john-hay.d69910f5.glb', 1, 0, 0 FROM "destinations" WHERE "slug" = 'camp-john-hay';
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION 'landmarks: camp-john-hay expected 1 row, inserted %', n; END IF;
  DELETE FROM "landmarks" WHERE "destination_id" = (SELECT "id" FROM "destinations" WHERE "slug" = 'diplomat-hotel-ruins');
  INSERT INTO "landmarks" ("id", "destination_id", "mesh_url", "mesh_scale", "rotation_deg", "altitude_m")
  SELECT gen_random_uuid()::text, "id", '/models/landmarks/diplomat-hotel-ruins.a75c520e.glb', 1, 0, 0 FROM "destinations" WHERE "slug" = 'diplomat-hotel-ruins';
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION 'landmarks: diplomat-hotel-ruins expected 1 row, inserted %', n; END IF;
  DELETE FROM "landmarks" WHERE "destination_id" = (SELECT "id" FROM "destinations" WHERE "slug" = 'good-shepherd-convent');
  INSERT INTO "landmarks" ("id", "destination_id", "mesh_url", "mesh_scale", "rotation_deg", "altitude_m")
  SELECT gen_random_uuid()::text, "id", '/models/landmarks/good-shepherd-convent.c8bbc6a1.glb', 1, 0, 0 FROM "destinations" WHERE "slug" = 'good-shepherd-convent';
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION 'landmarks: good-shepherd-convent expected 1 row, inserted %', n; END IF;
  DELETE FROM "landmarks" WHERE "destination_id" = (SELECT "id" FROM "destinations" WHERE "slug" = 'igorot-stone-kingdom');
  INSERT INTO "landmarks" ("id", "destination_id", "mesh_url", "mesh_scale", "rotation_deg", "altitude_m")
  SELECT gen_random_uuid()::text, "id", '/models/landmarks/igorot-stone-kingdom.68cc089c.glb', 1, 0, 0 FROM "destinations" WHERE "slug" = 'igorot-stone-kingdom';
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION 'landmarks: igorot-stone-kingdom expected 1 row, inserted %', n; END IF;
  DELETE FROM "landmarks" WHERE "destination_id" = (SELECT "id" FROM "destinations" WHERE "slug" = 'la-trinidad-strawberry-farms');
  INSERT INTO "landmarks" ("id", "destination_id", "mesh_url", "mesh_scale", "rotation_deg", "altitude_m")
  SELECT gen_random_uuid()::text, "id", '/models/landmarks/la-trinidad-strawberry-farms.dce0534d.glb', 1, 0, 0 FROM "destinations" WHERE "slug" = 'la-trinidad-strawberry-farms';
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION 'landmarks: la-trinidad-strawberry-farms expected 1 row, inserted %', n; END IF;
  DELETE FROM "landmarks" WHERE "destination_id" = (SELECT "id" FROM "destinations" WHERE "slug" = 'lions-head-kennon-road');
  INSERT INTO "landmarks" ("id", "destination_id", "mesh_url", "mesh_scale", "rotation_deg", "altitude_m")
  SELECT gen_random_uuid()::text, "id", '/models/landmarks/lions-head-kennon-road.554a9d53.glb', 1, 0, 0 FROM "destinations" WHERE "slug" = 'lions-head-kennon-road';
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION 'landmarks: lions-head-kennon-road expected 1 row, inserted %', n; END IF;
  DELETE FROM "landmarks" WHERE "destination_id" = (SELECT "id" FROM "destinations" WHERE "slug" = 'lourdes-grotto');
  INSERT INTO "landmarks" ("id", "destination_id", "mesh_url", "mesh_scale", "rotation_deg", "altitude_m")
  SELECT gen_random_uuid()::text, "id", '/models/landmarks/lourdes-grotto.2a2b7e4a.glb', 1, 0, 0 FROM "destinations" WHERE "slug" = 'lourdes-grotto';
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION 'landmarks: lourdes-grotto expected 1 row, inserted %', n; END IF;
  DELETE FROM "landmarks" WHERE "destination_id" = (SELECT "id" FROM "destinations" WHERE "slug" = 'mile-hi-cjh-viewdeck');
  INSERT INTO "landmarks" ("id", "destination_id", "mesh_url", "mesh_scale", "rotation_deg", "altitude_m")
  SELECT gen_random_uuid()::text, "id", '/models/landmarks/mile-hi-cjh-viewdeck.cb571363.glb', 1, 0, 0 FROM "destinations" WHERE "slug" = 'mile-hi-cjh-viewdeck';
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION 'landmarks: mile-hi-cjh-viewdeck expected 1 row, inserted %', n; END IF;
  DELETE FROM "landmarks" WHERE "destination_id" = (SELECT "id" FROM "destinations" WHERE "slug" = 'mines-view-park');
  INSERT INTO "landmarks" ("id", "destination_id", "mesh_url", "mesh_scale", "rotation_deg", "altitude_m")
  SELECT gen_random_uuid()::text, "id", '/models/landmarks/mines-view-park.a4bb74df.glb', 1, 0, 0 FROM "destinations" WHERE "slug" = 'mines-view-park';
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION 'landmarks: mines-view-park expected 1 row, inserted %', n; END IF;
  DELETE FROM "landmarks" WHERE "destination_id" = (SELECT "id" FROM "destinations" WHERE "slug" = 'philippine-military-academy');
  INSERT INTO "landmarks" ("id", "destination_id", "mesh_url", "mesh_scale", "rotation_deg", "altitude_m")
  SELECT gen_random_uuid()::text, "id", '/models/landmarks/philippine-military-academy.d909aae9.glb', 1, 0, 0 FROM "destinations" WHERE "slug" = 'philippine-military-academy';
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION 'landmarks: philippine-military-academy expected 1 row, inserted %', n; END IF;
  DELETE FROM "landmarks" WHERE "destination_id" = (SELECT "id" FROM "destinations" WHERE "slug" = 'session-road');
  INSERT INTO "landmarks" ("id", "destination_id", "mesh_url", "mesh_scale", "rotation_deg", "altitude_m")
  SELECT gen_random_uuid()::text, "id", '/models/landmarks/session-road.53cf8d5e.glb', 1, 0, 0 FROM "destinations" WHERE "slug" = 'session-road';
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION 'landmarks: session-road expected 1 row, inserted %', n; END IF;
  DELETE FROM "landmarks" WHERE "destination_id" = (SELECT "id" FROM "destinations" WHERE "slug" = 'tam-awan-village');
  INSERT INTO "landmarks" ("id", "destination_id", "mesh_url", "mesh_scale", "rotation_deg", "altitude_m")
  SELECT gen_random_uuid()::text, "id", '/models/landmarks/tam-awan-village.cd6e918d.glb', 1, 0, 0 FROM "destinations" WHERE "slug" = 'tam-awan-village';
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION 'landmarks: tam-awan-village expected 1 row, inserted %', n; END IF;
  DELETE FROM "landmarks" WHERE "destination_id" = (SELECT "id" FROM "destinations" WHERE "slug" = 'teachers-camp');
  INSERT INTO "landmarks" ("id", "destination_id", "mesh_url", "mesh_scale", "rotation_deg", "altitude_m")
  SELECT gen_random_uuid()::text, "id", '/models/landmarks/teachers-camp.61783be3.glb', 1, 0, 0 FROM "destinations" WHERE "slug" = 'teachers-camp';
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION 'landmarks: teachers-camp expected 1 row, inserted %', n; END IF;
  DELETE FROM "landmarks" WHERE "destination_id" = (SELECT "id" FROM "destinations" WHERE "slug" = 'the-mansion');
  INSERT INTO "landmarks" ("id", "destination_id", "mesh_url", "mesh_scale", "rotation_deg", "altitude_m")
  SELECT gen_random_uuid()::text, "id", '/models/landmarks/the-mansion.9d648e8d.glb', 1, 0, 0 FROM "destinations" WHERE "slug" = 'the-mansion';
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION 'landmarks: the-mansion expected 1 row, inserted %', n; END IF;
  DELETE FROM "landmarks" WHERE "destination_id" = (SELECT "id" FROM "destinations" WHERE "slug" = 'wright-park');
  INSERT INTO "landmarks" ("id", "destination_id", "mesh_url", "mesh_scale", "rotation_deg", "altitude_m")
  SELECT gen_random_uuid()::text, "id", '/models/landmarks/wright-park.e0ec67af.glb', 1, 0, 0 FROM "destinations" WHERE "slug" = 'wright-park';
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION 'landmarks: wright-park expected 1 row, inserted %', n; END IF;
END
$$;
