-- Landmark meshes, generated by model/scripts/landmarks_sql.py from model/out/landmarks-manifest.json.
-- Live destination ids differ from the seed's, so rows are matched by slug. Idempotent.
DO $$
DECLARE n integer;
BEGIN
  DELETE FROM "landmarks" WHERE "destination_id" = (SELECT "id" FROM "destinations" WHERE "slug" = 'baguio-cathedral');
  INSERT INTO "landmarks" ("id", "destination_id", "mesh_url", "mesh_scale", "rotation_deg", "altitude_m")
  SELECT gen_random_uuid()::text, "id", '/models/landmarks/baguio-cathedral.578796e0.glb', 1, 0, 0 FROM "destinations" WHERE "slug" = 'baguio-cathedral';
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION 'landmarks: baguio-cathedral expected 1 row, inserted %', n; END IF;
END
$$;
